language: ruby
cache: bundler
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.6

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      -taiwo.kareem36@gmail.com
    on_failure: change
    on_success: never